apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: neki
  labels:
    project: neki-ecommerce
type: Opaque
stringData:
  jwt-secret-key: REPLACE_WITH_JWT_SECRET_KEY
  payos-client-id: REPLACE_WITH_PAYOS_CLIENT_ID
  payos-api-key: REPLACE_WITH_PAYOS_API_KEY
  payos-checksum-key: REPLACE_WITH_PAYOS_CHECKSUM_KEY
  cloudinary-cloud-name: REPLACE_WITH_CLOUDINARY_CLOUD_NAME
  cloudinary-api-key: REPLACE_WITH_CLOUDINARY_API_KEY
  cloudinary-api-secret: REPLACE_WITH_CLOUDINARY_API_SECRET
