apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: neki
  labels:
    project: neki-ecommerce
type: Opaque
stringData:
  mysql-root-password: REPLACE_WITH_MYSQL_ROOT_PASSWORD
  postgres-user: REPLACE_WITH_POSTGRES_USER
  postgres-password: REPLACE_WITH_POSTGRES_PASSWORD
  rabbitmq-user: REPLACE_WITH_RABBITMQ_USER
  rabbitmq-password: REPLACE_WITH_RABBITMQ_PASSWORD
