server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push
    tenant_id: ""
    batchwait: 1s
    batchsize: 1048576

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: name
            values:
              - "neki-.*"

    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/?(.*)'
        target_label: 'container'

      - source_labels: ['__meta_docker_container_name']
        regex: '/?neki-(.*)'
        target_label: 'service'

      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'stream'

    pipeline_stages:
      - static_labels:
          env: local
          project: neki-ecommerce

      - multiline:
          firstline: '^\d{4}-\d{2}-\d{2}[T ]?\d{2}:\d{2}:\d{2}'
          max_wait_time: 3s
          max_lines: 128

      - regex:
          expression: '(?P<timestamp>\d{4}-\d{2}-\d{2}[T ]?\d{2}:\d{2}:\d{2}[\.,]?\d*)\s+(?P<level>(TRACE|DEBUG|INFO|WARN|ERROR|FATAL))\s+'

      - labels:
          level:

      - json:
          expressions:
            level: level
            logger: logger_name
            thread: thread_name
            traceId: traceId
            spanId: spanId
          source: output

      - labels:
          level:
          logger:
          traceId:

      - labeldrop:
          - filename
