server:
  port: 8084

spring:
  application:
    name: payment-service
  datasource:
    url: "${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/payments_db}"
    driver-class-name: org.postgresql.Driver
    username: "${SPRING_DATASOURCE_USERNAME:postgres}"
    password: "${SPRING_DATASOURCE_PASSWORD:}"
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: "${SPRING_RABBITMQ_HOST:localhost}"
    port: "${SPRING_RABBITMQ_PORT:5672}"
    username: "${SPRING_RABBITMQ_USERNAME:guest}"
    password: "${SPRING_RABBITMQ_PASSWORD:guest}"

eureka:
  client:
    service-url:
      defaultZone: "${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}"
  instance:
    prefer-ip-address: true

PAYOS:
  PAYOS_CLIENT_ID: "${PAYOS_PAYOS_CLIENT_ID}"
  PAYOS_API_KEY: "${PAYOS_PAYOS_API_KEY}"
  PAYOS_CHECKSUM_KEY: "${PAYOS_PAYOS_CHECKSUM_KEY}"

URL:
  returnUrl: "${URL_RETURNURL:http://localhost:5173/success}"
  cancelUrl: "${URL_CANCELURL:http://localhost:5173/cancel}"

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: "${MANAGEMENT_OTLP_TRACING_ENDPOINT:http://localhost:4318/v1/traces}"
