apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-registry
  namespace: neki
  labels:
    app: service-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-registry
  template:
    metadata:
      labels:
        app: service-registry
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: service-registry
          image: ghcr.io/thacbaonguyen/neki-service-registry:latest
          ports:
            - containerPort: 8761
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            initialDelaySeconds: 40
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: service-registry
  namespace: neki
spec:
  selector:
    app: service-registry
  ports:
    - port: 8761
      targetPort: 8761
  type: ClusterIP
