apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: neki
  labels:
    app: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: product-service
          image: ghcr.io/thacbaonguyen/neki-product-service:latest
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql:3306/products_db"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: mysql-root-password
            - name: SPRING_DATA_REDIS_HOST
              value: "redis"
            - name: SPRING_RABBITMQ_HOST
              value: "rabbitmq"
            - name: SPRING_ELASTICSEARCH_URIS
              value: "http://elasticsearch:9200"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://service-registry:8761/eureka/"
            - name: CLOUDINARY_CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: cloudinary-cloud-name
            - name: CLOUDINARY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: cloudinary-api-key
            - name: CLOUDINARY_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: cloudinary-api-secret
            - name: MANAGEMENT_OTLP_TRACING_ENDPOINT
              value: "http://tempo.monitoring:4317"
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 40
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 50
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: neki
spec:
  selector:
    app: product-service
  ports:
    - port: 8082
      targetPort: 8082
  type: ClusterIP
